### ISSUE TITLE
Modify `attach()` to randomly shuffle data?

### ISSUE THREAD

**Issue by zkamvar** [Ironholds/jammr#5]
I was thinking something along the lines of:

``` r
  replace("attach", function(what, pos = 2L, name = deparse(substitute(what)), warn.conflicts = TRUE) {
    if (runif(1) < 0.5) {
      what[] <- lapply(what, sample)
    } 
    attach(what, pos = 2L, name = deparse(substitute(what)), warn.conflicts = TRUE)
  })
```

Note: I don't know if this would work.

**Comment by Ironholds** [comment]
Is "attach" the one people use instead of library() or am I thinking of something else?

**Comment by zkamvar** [comment]
You're thinking of `require()`. Attach is the one that people use to make columns in data frames accessible without using `$` or `[[`. It is famously known to cause problems on its own: http://www.r-bloggers.com/to-attach-or-not-attach-that-is-the-question/

example:

``` r
data(iris)
attach(iris)
Species # equivalent to iris$Species
detach(iris)
Species # error
```
